package it.si3p.supwsd.config;

/**
 * @author papandrea
 *
 */
public enum ConfigTag {

	SUPWSD, WORKING_DIRECTORY, PARSER, PREPROCESSING, PIPELINE, SPLITTER, TOKENIZER, TAGGER, LEMMATIZER, DEPENDENCY_PARSER, EXTRACTION, FEATURES, POS_TAGS, LOCAL_COLLOCATIONS, SURROUNDING_WORDS, WORD_EMBEDDINGS, SYNTACTIC_RELATIONS, CLASSIFIER, WRITER, SENSE_INVENTORY;

}